from fpdf import FPDF
import os

def generate_pdf_report(summary, score, feedback, match_score=None, ai_summary=None, keywords=None, probability=None, template=None, template_text=None, filename="Resume_Report.pdf"):
    pdf = FPDF()
    pdf.add_page()
    # Title
    pdf.set_font("Arial", size=16, style='B')
    pdf.cell(0, 12, "Resume Analysis Report", ln=True, align='C')
    pdf.ln(6)

    # Section: Summary
    pdf.set_font("Arial", size=13, style='B')
    pdf.cell(0, 10, "1. Summary", ln=True)
    pdf.set_font("Arial", size=12)
    pdf.multi_cell(0, 9, summary)
    pdf.ln(2)

    # Section: Score & Probability
    pdf.set_font("Arial", size=13, style='B')
    pdf.cell(0, 10, "2. Score & Probability", ln=True)
    pdf.set_font("Arial", size=12)
    pdf.cell(0, 9, f"Score: {score} / 10", ln=True)
    if match_score is not None:
        pdf.cell(0, 9, f"Job Match Score: {match_score}%", ln=True)
    if probability is not None:
        pdf.cell(0, 9, f"Estimated Selection Probability: {probability}%", ln=True)
    pdf.ln(2)

    # Section: Feedback
    pdf.set_font("Arial", size=13, style='B')
    pdf.cell(0, 10, "3. Feedback", ln=True)
    pdf.set_font("Arial", size=12)
    if feedback:
        for item in feedback:
            pdf.multi_cell(0, 9, f"- {item}")
    else:
        pdf.cell(0, 9, "No feedback.", ln=True)
    pdf.ln(2)

    # Section: Top Keywords
    if keywords:
        pdf.set_font("Arial", size=13, style='B')
        pdf.cell(0, 10, "4. Top Keywords Extracted", ln=True)
        pdf.set_font("Arial", size=12)
        pdf.multi_cell(0, 9, ", ".join(keywords))
        pdf.ln(2)

    # Section: Resume Template Suggestion
    if template:
        pdf.set_font("Arial", size=13, style='B')
        pdf.cell(0, 10, "5. Suggested Resume Template", ln=True)
        pdf.set_font("Arial", size=12, style='B')
        pdf.cell(0, 9, f"Type: {template}", ln=True)
        pdf.set_font("Arial", size=12)
        if template_text:
            pdf.multi_cell(0, 9, template_text)

    # Footer
    pdf.set_y(-20)
    pdf.set_font("Arial", size=10, style='I')
    pdf.cell(0, 10, "Generated by AI Resume Analyzer", 0, 0, 'C')

    path = os.path.join("uploads", filename)
    pdf.output(path)
    return path
